#!/usr/bin/env python3
"""Fix insertions for refresh #8"""
import re

DATA_FILE = "client/src/data/philly-data.ts"

with open(DATA_FILE, "r") as f:
    content = f.read()

new_events_ts = """  {
    id: "event-121",
    name: "Snarky Puppy at Union Transfer",
    date: "2026-04-17",
    time: "8:00 PM",
    venue: "Union Transfer",
    address: "1026 Spring Garden Street, Philadelphia, PA 19123",
    neighborhood: "Spring Garden",
    category: "music",
    description: "Grammy-winning fusion collective Snarky Puppy brings their genre-defying live show to Union Transfer with The Nth Power opening. Known for jaw-dropping improvisation blending jazz, funk, world music, and prog -- their live sets are legendary and this mid-size room is the perfect setting.",
    price: "$35+",
    vibeTag: "insider",
    source: "utphilly.com / ticketmaster.com",
    lat: 39.9618,
    lng: -75.1541,
    isInsider: true,
  },
  {
    id: "event-122",
    name: "Snow Tha Product at Union Transfer",
    date: "2026-04-10",
    time: "8:00 PM",
    venue: "Union Transfer",
    address: "1026 Spring Garden Street, Philadelphia, PA 19123",
    neighborhood: "Spring Garden",
    category: "music",
    description: "Bilingual rap powerhouse Snow Tha Product brings her viral energy and rapid-fire flows to Union Transfer. One of the most dynamic performers in hip-hop right now, with a devoted fanbase and a live show that never lets up.",
    price: "$30+",
    vibeTag: "underground",
    source: "bowerypresents.com / axs.com",
    lat: 39.9618,
    lng: -75.1541,
    isInsider: true,
  },
  {
    id: "event-123",
    name: "Jose Gonzalez at Union Transfer",
    date: "2026-04-22",
    time: "8:00 PM",
    venue: "Union Transfer",
    address: "1026 Spring Garden Street, Philadelphia, PA 19123",
    neighborhood: "Spring Garden",
    category: "music",
    description: "Swedish-Argentine singer-songwriter Jose Gonzalez performs with Abby Sage, presented by WXPN 88.5. His delicate acoustic guitar work and haunting vocals fill a room like few performers can. An intimate, seated-vibe show at one of Philly\\'s best mid-size venues.",
    price: "$35+",
    vibeTag: "insider",
    source: "axs.com / seatgeek.com",
    lat: 39.9618,
    lng: -75.1541,
    isInsider: true,
  },
  {
    id: "event-124",
    name: "Lotus at Union Transfer",
    date: "2026-04-18",
    time: "8:00 PM",
    venue: "Union Transfer",
    address: "1026 Spring Garden Street, Philadelphia, PA 19123",
    neighborhood: "Spring Garden",
    category: "music",
    description: "Electronic jam band Lotus returns to Union Transfer for a Saturday night of pulsing synths, intricate guitar work, and deep grooves. A Philly-area band with a massive grassroots following -- their UT shows always sell out and the energy is electric.",
    price: "$25+",
    vibeTag: "local-favorite",
    source: "concertfix.com / utphilly.com",
    lat: 39.9618,
    lng: -75.1541,
    isInsider: true,
  },
  {
    id: "event-125",
    name: "Naika at Underground Arts",
    date: "2026-04-11",
    time: "8:30 PM",
    venue: "Underground Arts",
    address: "1200 Callowhill Street, Philadelphia, PA 19123",
    neighborhood: "Callowhill",
    category: "music",
    description: "Haitian-American R&B and soul artist Naika brings her rich, genre-blending sound to Underground Arts. Mixing R&B, Haitian kompa, and indie pop, she is one of the most exciting rising voices in Philly\\'s music scene right now.",
    price: "$25+",
    vibeTag: "underground",
    source: "undergroundarts.org / concertfix.com",
    lat: 39.9590,
    lng: -75.1580,
    isInsider: true,
  },
  {
    id: "event-126",
    name: "Sports. at Underground Arts",
    date: "2026-04-04",
    time: "8:30 PM",
    venue: "Underground Arts",
    address: "1200 Callowhill Street, Philadelphia, PA 19123",
    neighborhood: "Callowhill",
    category: "music",
    description: "Oklahoma indie pop duo Sports. bring their shimmering, synth-driven dream pop to Underground Arts. Warm melodies, retro production, and a feel-good live show perfect for a Saturday night out in Callowhill.",
    price: "$20+",
    vibeTag: "underground",
    source: "undergroundarts.org / concertfix.com",
    lat: 39.9590,
    lng: -75.1580,
    isInsider: true,
  },
  {
    id: "event-127",
    name: "Blood for Blood at Underground Arts",
    date: "2026-04-09",
    time: "7:00 PM",
    venue: "Underground Arts",
    address: "1200 Callowhill Street, Philadelphia, PA 19123",
    neighborhood: "Callowhill",
    category: "music",
    description: "Boston hardcore legends Blood for Blood hit Underground Arts with Skinhead, Conservative, Military Image, and FLPSDE. All ages, $30 advance. A raw, no-frills hardcore show that will shake the walls -- not for the faint of heart.",
    price: "$30",
    vibeTag: "underground",
    source: "facebook.com/PhillyHardcoreShows",
    lat: 39.9590,
    lng: -75.1580,
    isInsider: true,
  },
  {
    id: "event-128",
    name: "Rochelle Jordan at Theatre of Living Arts",
    date: "2026-03-24",
    time: "8:00 PM",
    venue: "Theatre of Living Arts",
    address: "334 South Street, Philadelphia, PA 19147",
    neighborhood: "South Street",
    category: "music",
    description: "Canadian R&B innovator Rochelle Jordan performs at the TLA tonight. Known for blending 90s R&B nostalgia with UK garage and house production, her live shows are a vibe -- lush vocals over pulsing electronic beats in an intimate setting.",
    price: "$25+",
    vibeTag: "underground",
    source: "seatgeek.com",
    lat: 39.9427,
    lng: -75.1487,
    isInsider: true,
  },
  {
    id: "event-129",
    name: "Bryant Barnes at The Fillmore Philadelphia",
    date: "2026-03-25",
    time: "8:00 PM",
    venue: "The Fillmore Philadelphia",
    address: "29 E. Allen Street, Philadelphia, PA 19123",
    neighborhood: "Fishtown",
    category: "music",
    description: "Rising singer-songwriter Bryant Barnes brings his heartfelt blend of country, soul, and Americana to The Fillmore with RealestK opening. A fresh voice gaining serious momentum -- catch him before arenas.",
    price: "$25+",
    vibeTag: "trending",
    source: "seatgeek.com / livenation.com",
    lat: 39.9668,
    lng: -75.1340,
    isInsider: false,
  },
  {
    id: "event-130",
    name: "Jon B. at Theatre of Living Arts",
    date: "2026-03-27",
    time: "7:00 PM",
    venue: "Theatre of Living Arts",
    address: "334 South Street, Philadelphia, PA 19147",
    neighborhood: "South Street",
    category: "music",
    description: "90s R&B icon Jon B. takes the stage at the TLA with Sebastian Mikael. From \\'Someone to Love\\' to \\'They Don\\'t Know,\\' this is a night of smooth, soulful nostalgia on South Street. Friday night vibes guaranteed.",
    price: "$35+",
    vibeTag: "local-favorite",
    source: "seatgeek.com",
    lat: 39.9427,
    lng: -75.1487,
    isInsider: false,
  },
"""

new_hotspots_ts = """  {
    id: "spot-81",
    name: "LynUp Cafe & Lounge",
    type: "restaurant",
    address: "7803 Frankford Avenue, Philadelphia, PA 19136",
    neighborhood: "Northeast Philadelphia",
    description: "A fashionable West African BYOB serving bold, flavorful dishes in a vibrant setting. One of the few West African restaurants in the city and a community gathering spot in the Northeast. Bringing something genuinely different to Philly\\'s dining scene.",
    vibeTag: "insider",
    priceRange: "$$",
    cuisine: "West African",
    isNew: true,
    isInsider: true,
    lat: 40.0372,
    lng: -75.0485,
    source: "visitphilly.com",
  },
  {
    id: "spot-82",
    name: "Casa Oui",
    type: "restaurant",
    address: "705 S. 5th Street, Philadelphia, PA 19147",
    neighborhood: "Queen Village",
    description: "All-day cafe and bar in Queen Village serving tacos, salads, burgers (try the Casa Oui Burger with bacon, mozzarella, and secret sauce), plus a full coffee and cocktail menu. Indoor/outdoor vibes with a laid-back neighborhood feel.",
    vibeTag: "trendy",
    priceRange: "$$",
    cuisine: "New American / Mexican",
    isNew: true,
    isInsider: false,
    lat: 39.9395,
    lng: -75.1478,
    source: "visitphilly.com",
  },
  {
    id: "spot-83",
    name: "Solar Myth",
    type: "bar",
    address: "1131 S. Broad Street, Philadelphia, PA 19147",
    neighborhood: "South Broad",
    description: "Part wine bar, part music venue, part vinyl shop -- Solar Myth on South Broad is a multifaceted hangout. Coffee and tomato pie by day, natural wine and experimental jazz by night. The kind of place where you might see two people making out on a banquette at midnight.",
    vibeTag: "insider",
    priceRange: "$$",
    cuisine: null,
    isNew: false,
    isInsider: true,
    lat: 39.9347,
    lng: -75.1665,
    source: "theinfatuation.com",
  },
  {
    id: "spot-84",
    name: "Pretzel Day Pretzels",
    type: "bakery",
    address: "1541 South Street, Philadelphia, PA 19146",
    neighborhood: "Graduate Hospital",
    description: "A new power player in Philly\\'s soft pretzel game. Fresh-baked pretzels with creative toppings and dips in a no-frills shop that has quickly earned a loyal following. A must-visit for pretzel purists and adventurous snackers alike.",
    vibeTag: "local-favorite",
    priceRange: "$",
    cuisine: "Bakery / Pretzels",
    isNew: true,
    isInsider: false,
    lat: 39.9431,
    lng: -75.1729,
    source: "visitphilly.com",
  },
"""

# Use the correct markers with trailing comma
marker1 = '},\n];\n\nexport const hotspots: HotSpot[] = ['
marker2 = '},\n];\n\nexport const influencers: Influencer[] = ['

if marker1 in content:
    content = content.replace(marker1, '},\n' + new_events_ts + '];\n\nexport const hotspots: HotSpot[] = [')
    print("Events inserted successfully.")
else:
    print("ERROR: events marker not found!")

if marker2 in content:
    content = content.replace(marker2, '},\n' + new_hotspots_ts + '];\n\nexport const influencers: Influencer[] = [')
    print("Hotspots inserted successfully.")
else:
    print("ERROR: hotspots marker not found!")

with open(DATA_FILE, "w") as f:
    f.write(content)

final_events = len(re.findall(r'id: "event-\d+"', content))
final_hotspots = len(re.findall(r'id: "spot-\d+"', content))
print(f"\nFinal events: {final_events}")
print(f"Final hotspots: {final_hotspots}")
